### PR TITLE
Windows Performance Improvement & Multi-Item support

### PR DESCRIPTION
**Pull request by arsenetar**
- Use pywin32 to implement IFileOperation
- Add ability to allow passing a list of files to send2trash across all platforms
- Batch trash operations on windows for both IFileOperation and SHFileOperation

Notes:
- My code format plugin formatted the contents of the files I changed, let me know if this is an issue and I can back those out (it fixed some flake8 style issues as well)
- IFileOperation should open up the ability to address #28 but I'll add in the extras for that in another PR.

### CODE REVIEW

**Comment by BoboTiG** [comment]
Wow this is quite a PR :muscle: :)

Do you mind adding a test on Windows to force using the legacy implementation to be sure it is still tested?

**Comment by arsenetar** [comment]
Yeah it would be possible to try forcing the different versions, right now I am not sure which version the CI is actually testing, it looks like it is most likely still testing the legacy version, I'll see about getting the CI to install pywin32 and then test both versions.

**Comment by BoboTiG** [comment]
FTR the CI is using Windows Server 2019, so it will likely test the new implementation only.

**Comment by arsenetar** [comment]
Either way, I should be able to get it to run both, with the dependency on pywin32 even though it is a new enough version of the OS it will not run without that package installed.  I don't think the chocolatey python package includes anything different than the standard windows python installers, if that is the case it should be testing the legacy version based on what I have seen on Windows 10.

**Comment by hsoft** [comment]
@arsenetar this looks great and it's been a long time since these issues should have been tackled. You tackle them and it's excellent news.

As the README says, I'm looking for someone to take over this library. You're already doing a good job with dupeguru, would you mind taking this library too?

**Comment by hsoft** [comment]
Good! IIRC, we had problems during the last transfer because you had to delete your fork first. So I'll merge your PR right now and then let you delete your fork before proceeding.

Do you have a PyPI account? I'll transfer your publishing rights too.

**Comment by arsenetar** [comment]
I have remove my fork.  I did not have a PyPI account, I do now username is the same as here `arsenetar`.

**Comment by hsoft** [comment]
Transfer initiated. You've also been added as an owner of the pypi package.

**Comment by hsoft** [comment]
Good, goodspeed! :)

**Pull request merged**
