### PR TITLE
Workaround embedded null character

### LINKED ISSUE #17: Fails with python 3.6.3 on windows
I get the following when calling send2trash on python 3.6.3 on windows 7:
`File "...\AppData\Local\Programs\Python\Python36\lib\site-packages\send2trash\plat_win.py", line 49, in send2trash
fileop.pFrom = LPCWSTR(path + '\0')
ValueError: embedded null character
`

I'm pretty sure it didn't fail until I switched to 3.6.3. My guess is that [this](https://bugs.python.org/issue23908) fix is responsible.

### PR DESCRIPTION
**Pull request by arsenetar**
Workaround embedded null characters in strings.  This fixes #17.

### CODE REVIEW

**Comment by hsoft** [comment]
Good stuff, thanks.

**Comment by HWiese1980** [comment]
Are you going to update basic pip installation to include this workaround?

**Comment by hsoft** [comment]
@HWiese1980 yes. I'll release a new version in a couple of hours.

**Comment by hsoft** [comment]
Did I say "few hours"? I meant "I'll forget about it and remember it later" :) releasing now.

**Pull request merged**
